### ISSUE TITLE
yaml-cpp vendor fails to build with newest VS2017 15.8

### ISSUE THREAD

**Issue by Martin-Idel-SI** [ros2/rviz#350]
Problem: yaml-cpp won't build with newest Visual Studio. Error:
```
<...>\yaml-cpp\exceptions.h(149): error C3646: '_NOEXCEPT': unknown override specifier (compiling source file <...>\src\parse.cpp) [<...>\yaml-cpp.vcxproj]
```

There is already a fix upstream, but it's not released, yet:
https://github.com/jbeder/yaml-cpp/commit/0f9a586ca1dc29c2ecb8dd715a315b93e3f40f79

Either we have to apply the fix ourselves or wait for the next 0.6 release and upgrade.

**Comment by mikaelarguedas** [comment]
As we are already using a specific commit hash for yaml-cpp, would it be worth trying the latest master just to see if it builds successfully pending the 0.6 release?

**Comment by mikaelarguedas** [comment]
thanks @Martin-Idel-SI for reporting and tracking down the right patch!

**Comment by Martin-Idel-SI** [comment]
Thanks! Works perfectly.
