### PR TITLE
Migrate Pose Display

### LINKED ISSUE #86: Migrate PoseDisplay

### PR DESCRIPTION
**Pull request by Martin-Idel-SI**
Resolves #86

### CODE REVIEW

**Comment by Martin-Idel-SI** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/3945/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1063/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3275/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4044/)

**Comment by greimela-si** [comment]
Rebased after changes on ros2 branch.

New CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/4021/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/1115/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/3348/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/4112/) (failures unrelated)

**Review by wjwwood — APPROVED** [review]
lgtm

**Comment by sloretz** [comment]
Missing header arrow.hpp? I got this error in a CI job

```
23:12:52 /home/rosbuild/ci_scripts/ws/src/ros2/rviz/rviz_default_plugins/src/rviz_default_plugins/displays/pose/pose_display.cpp:36:36: fatal error: rviz_rendering/arrow.hpp: No such file or directory
```

Edit: [failing build](https://ci.ros2.org/job/ci_linux/4032/console)

edit 2: I don't see arrow.hpp in the [rviz_rendering package include folder](https://github.com/ros2/rviz/tree/ros2/rviz_rendering/include/rviz_rendering)

**Comment by sloretz** [comment]
Also missing axes.hpp. Should the include be `<rviz_rendering/objects/axes.hpp>` and `<rviz_rendering/objects/arrow.hpp>` instead?

```
23:11:51 /home/rosbuild/ci_scripts/ws/src/ros2/rviz/rviz_default_plugins/src/rviz_default_plugins/displays/pose/pose_display_selection_handler.cpp:42:35: fatal error: rviz_rendering/axes.hpp: No such file or directory
```

**Comment by wjwwood** [comment]
Weird, I built this locally, I guess the conflict resolution messed up somewhere. Let me look real quick.

**Comment by wjwwood** [comment]
I went ahead and reverted it until I can figure out what went wrong, sorry for the hiccup.

https://github.com/ros2/rviz/pull/227

**Comment by wjwwood** [comment]
@sloretz it was this other pr that moved the file, so individually they passed CI, but after merging both this one was broken:

https://github.com/ros2/rviz/pull/210/files#diff-d542aecef54d76e5d18642037240f2fd

I'll fix it up and run new CI for this one.

**Comment by sloretz** [comment]
Thanks @wjwwood 

Hard to spot a move in a +4800,-8200 :open_mouth:  PR

**Comment by wjwwood** [comment]
Well, and I built it locally, but not after merging the other pr. I guess technically we should rerun CI after every commit to the target branch (`ros2` in this case).
