### ISSUE TITLE
Master does not build with recent ros2 master

### ISSUE THREAD

**Issue by Martin-Idel-SI** [ros2/rviz#116]
The current rviz master cannot build with the latest ros2 master since the clock API was updated:
- https://github.com/ros2/rclcpp/commit/a215d2d22e03289705c6827d2ce8251e177d6353

In particular, `rclcpp::Time::now()` doesn't exist anymore, which leads to many errors in the build.

**Comment by yechun1** [comment]
I meet the same error while build on Linux ubuntu 16.04
error: no matching function for call to ‘rclcpp::Time::Time()’

Build log:
---
/root/ros2_ws/rviz_ws/rviz2/src/rviz/rviz_common/src/rviz_common/temp/robot/tf_link_updater.cpp:70:61: error: no matching function for call to ‘rclcpp::Time::Time()’
   if (!frame_manager_->getTransform(link_name, rclcpp::Time(), position, orientation)) {
                                                             ^
In file included from /root/ros2_ws/rviz_ws/rviz2/src/rviz/rviz_common/include/rviz_common/frame_manager.hpp:45:0,
                 from /root/ros2_ws/rviz_ws/rviz2/src/rviz/rviz_common/src/rviz_common/temp/robot/tf_link_updater.cpp:39:
/root/ros2_ws/core_beta3/install/include/rclcpp/time.hpp:45:3: note: candidate: rclcpp::Time::Time(const Time&)
(...)
CMakeFiles/rviz_common.dir/build.make:134: recipe for target 'CMakeFiles/rviz_common.dir/src/rviz_common/temp/robot/tf_link_updater.cpp.o' failed
make[2]: *** [CMakeFiles/rviz_common.dir/src/rviz_common/temp/robot/tf_link_updater.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/rviz_common.dir/all' failed
make[1]: *** [CMakeFiles/rviz_common.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

---
