### ISSUE TITLE
rviz_assimp_vendor build fails on Fedora 44 / GCC 15.1.1: -Werror=unused-but-set-variable in MS3DLoader.cpp

### ISSUE THREAD

**Issue by nickschuetz** [ros2/rviz#1730]
## Symptom

`rviz_assimp_vendor` fails to build on Fedora 44 (GCC 15.1.1) due to `-Werror=unused-but-set-variable` triggered by upstream Assimp's `MS3DLoader.cpp`. The `-Wno-error` flag I tried passing in my downstream spec gets overridden by Assimp's bundled CMake, which appends its own `-Werror` to the compile flags later in the command line.

## Build environment

- Fedora 44 x86_64 (mock chroot)
- GCC 15.1.1
- CMake 4.0.3
- ninja 1.13
- `rviz_assimp_vendor` from `release/jazzy/rviz_assimp_vendor/14.1.20-2`
- Vendored Assimp version is 5.x (per `rviz_assimp_vendor/CMakeLists.txt`, the `assimp_vendor` ExternalProject)

## Error excerpt

```
[N/250] /usr/bin/g++ ... -c .../code/AssetLib/MS3D/MS3DLoader.cpp
.../code/AssetLib/MS3D/MS3DLoader.cpp:639:28: error: variable 'qu' set but not used [-Werror=unused-but-set-variable=]
  639 |                 aiQuatKey* qu = nd->mRotationKeys;
      |                            ^~
cc1plus: all warnings being treated as errors
ninja: build stopped: subcommand failed.
```

(`MS3DLoader.cpp:639`, `aiQuatKey* qu = nd->mRotationKeys;` is set but never read after that point.)

## Why downstream `-Wno-error` doesn't reach this

I tried setting `CXXFLAGS="$CXXFLAGS -Wno-error"` in the spec's `%build` and also `-DCMAKE_CXX_FLAGS="-Wno-error"` on the outer `cmake` invocation. Both reach the outer `rviz_assimp_vendor` build, but the inner ExternalProject (Assimp itself) propagates them through its own CMake and then **appends its own `-Werror`** later in the per-target compile flags:

```
... -Wno-error -std=gnu++17 -fPIC -Wno-dangling-reference -Wall -Werror -MD -MT ...
                ^^^^^^^^^^                                       ^^^^^^^
                ours, then immediately overridden by Assimp's
```

So the override has to happen inside the ExternalProject's CMake invocation, not in the outer `rviz_assimp_vendor` flags.

## Proposed fix in `rviz_assimp_vendor`

The cleanest workaround on the rviz side, while waiting for the real fix upstream in `assimp/assimp`, is to extend the existing `ASSIMP_CXX_FLAGS` list in `rviz_assimp_vendor/CMakeLists.txt` so the inner Assimp build picks up `-Wno-error=unused-but-set-variable`. Roughly:

```diff
diff --git a/rviz_assimp_vendor/CMakeLists.txt b/rviz_assimp_vendor/CMakeLists.txt
@@ -... existing ASSIMP_CXX_FLAGS settings ...
   set(ASSIMP_CXX_FLAGS "-std=c++14 ${CMAKE_CXX_FLAGS}")
+  set(ASSIMP_CXX_FLAGS "-Wno-error=unused-but-set-variable ${ASSIMP_CXX_FLAGS}")
   set(ASSIMP_C_FLAGS   "-Wno-deprecated-non-prototype ${CMAKE_C_FLAGS}")
```

Possibly also adding `-Wno-error=array-bounds` and `-Wno-error=dangling-reference` defensively. These are GCC 13/14/15 issues that other downstream packagers have hit (see [assimp/assimp#6042](https://github.com/assimp/assimp/issues/6042) and [#6144](https://github.com/assimp/assimp/issues/6144)).

## Real upstream fix

The real fix belongs in [`assimp/assimp`](https://github.com/assimp/assimp), either:
1. Drop the dead `qu` variable in `code/AssetLib/MS3D/MS3DLoader.cpp:639` (one-line patch), or
2. Stop unconditionally adding `-Werror` to Assimp's own targets, or gate it behind a `BUILD_DEBUG` / `ASSIMP_WARNINGS_AS_ERRORS` option.

I haven't filed that separately yet. Figured it's worth getting alignment on the rviz-side workaround first since `rviz_assimp_vendor` builds the vendored Assimp from a pinned commit anyway.

## System library substitution doesn't help

Fedora ships `assimp-devel-6.0.4` which is incompatibly newer than the 5.x that `rviz_assimp_vendor` pins. Sticking with the vendored ExternalProject is the right call; we just need it to build under modern GCC.

## Why this matters downstream

Companion to #1637 / #1708 (the Ogre CMake 4.x issue, already in flight). With both resolved, `rviz_assimp_vendor` and `rviz_ogre_vendor` build cleanly on Fedora 44, which unblocks rviz2 packaging in [`hellaenergy/ros2`](https://copr.fedorainfracloud.org/coprs/hellaenergy/ros2), a development-only Fedora COPR for ROS 2 Jazzy. The same fix would also apply to Open Robotics's eventual official Fedora Lyrical packaging.

Happy to send a PR with the diff above (or a more complete one) if maintainers agree on the approach.
